### PR TITLE
Create amog

### PR DESCRIPTION
**Pull request by 13umpadump**

### CODE REVIEW

**Comment by mobilegmYT** [comment]
sus

**Comment by mobilegmYT** [comment]
Also whats da purpose of dis

**Comment by moon1789** [comment]
vat

**Review by approachcircle — APPROVED** [review]

**Comment by moon1789** [comment]
vat

**Comment by DocdoZach** [comment]
we need to do what it says

**Comment by DocdoZach** [comment]
WE MUST CREATE AMOG

**Comment by felixbennett** [comment]
when the imposter is **SUS??????**

**Comment by Crewmategamingcoding** [comment]
two trucks having sex

**Pull request closed without merging**
