### PR TITLE
fix things

### PR DESCRIPTION
**Pull request by joebobbio**
i forgo what all i did but i think it was a lot

### CODE REVIEW

**Comment by joebobbio** [comment]
Ok :p

**Comment by mobilegmYT** [comment]
Wait shit I read your PR wrong sowwy senpaii

**Comment by mobilegmYT** [comment]
Aaand of course there's a merge conflict

**Comment by joebobbio** [comment]
Reverse the other fix

**Comment by buddyjojo** [comment]
nooz cant we just do the fixes ourself?

**Comment by buddyjojo** [comment]
actually you know what i will

**Comment by buddyjojo** [comment]
or not

**Comment by buddyjojo** [comment]
there

**Pull request merged**
